# Download Repos, build and check LLVM, build and check ONNX MLIR

parameters:
- name: CMakeBuildTarget
  type: string
  default: ''
- name: CMakeExternalLIT
  type: string
  default: ''
- name: CMakePrefixPath
  type: string
  default: ''
- name: GeneratorString
  type: string
  default: 'Ninja'
- name: PythonExePath
  type: string
  default: '/usr/bin/python3'


steps:
  - checkout: self
    submodules: recursive
  - checkout: llvm-project
  - task: CMake@1
    displayName: 'CMake LLVM'
    inputs:
      workingDirectory: '$(LLVMBuildDir)'
      cmakeArgs: >-
        -G ${{ parameters.GeneratorString }}
        $(LLVMSourceDir)/llvm
        -DLLVM_ENABLE_PROJECTS=mlir
        -DLLVM_BUILD_EXAMPLES=ON
        -DLLVM_TARGETS_TO_BUILD="host;Apollo"
        -DCMAKE_BUILD_TYPE=$(CMakeBuildConfiguration)
        -DLLVM_ENABLE_ASSERTIONS=ON
        -DLLVM_ENABLE_RTTI=ON
        $(LLVMAdditionalCMakeOptions)

  - task: CMake@1
    displayName: 'Build LLVM'
    inputs:
      workingDirectory: '$(LLVMBuildDir)'
      cmakeArgs: '--build . --config $(CMakeBuildConfiguration)'

  - task: CMake@1
    displayName: 'Check LLVM'
    inputs:
      workingDirectory: '$(LLVMBuildDir)'
      cmakeArgs: '--build . --config $(CMakeBuildConfiguration) --target check-mlir'

  # Delete the current build directory. This is a temporary workaround until dependency
  # issues are resolved, although cost is low since ONNX MLIR builds quickly.
  - task: DeleteFiles@1
    displayName: 'Delete ONNX MLIR Build Directory'
    inputs:
      SourceFolder: '$(ONNXMLIRBuildDir)_$(CMakeBuildConfiguration)'
      Contents: '**/*' 
      RemoveSourceFolder: false

  - task: CMake@1
    displayName: 'CMake ONNX MLIR'
    inputs:
      workingDirectory: '$(ONNXMLIRBuildDir)_$(CMakeBuildConfiguration)'
      cmakeArgs: >-
        -G ${{ parameters.GeneratorString }}
        $(ONNXMLIRSourceDir)
        ${{ parameters.CMakeExternalLIT }}
        -DCMAKE_BUILD_TYPE=$(CMakeBuildConfiguration)
        -DADO_DOWNLOAD_ONNX_TEST_FILES=ON
        -DPYTHON_EXECUTABLE=${{ parameters.PythonExePath }}
        -DCMAKE_PREFIX_PATH=${{ parameters.CMakePrefixPath }}

  - task: CMake@1
    displayName: 'Build ONNX MLIR'
    inputs:
      workingDirectory: '$(ONNXMLIRBuildDir)_$(CMakeBuildConfiguration)'
      cmakeArgs: '--build . --config $(CMakeBuildConfiguration) --target ${{ parameters.CMakeBuildTarget }}'

  - task: CMake@1
    displayName: 'Check ONNX MLIR'
    inputs:
      workingDirectory: '$(ONNXMLIRBuildDir)_$(CMakeBuildConfiguration)'
      cmakeArgs: '--build . --config $(CMakeBuildConfiguration) --target check-onnx-lit'
