name: ONNX_MLIR.$(Build.SourceBranchName).${{ parameters.BuildLabel }}.$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

resources:
  repositories:
  - repository: llvm-project
    type: git
    name: llvm-project
    ref: refs/heads/tvp
  - repository: tools
    type: git
    name: tools
    ref: refs/heads/main
  - repository: protobuf
    type: github
    name: protocolbuffers/protobuf
    endpoint: ProtobufGitHubServiceConnection
    ref: refs/tags/v3.12.3

trigger: none

parameters:
- name: Platforms
  type: object
  default: ['Ubuntu', 'Windows']
- name: BuildConfigurations
  type: object
  default: ['Release']
- name: BuildLabel
  type: string
  default: 'Manual'
- name: RunAllTests
  type: boolean
  default: false

variables:
- name: System.PreferGitFromPath
  value: true

jobs:
- template: .azure-pipelines/templates/ONNXMLIRJobTemplate.yml@tools
  parameters:
    BuildConfigurations: ${{ parameters.BuildConfigurations }}
    Platforms: ${{ parameters.Platforms }}
    RunAllTests: ${{ parameters.RunAllTests }}
